defaults:
  - _self_

paths:
  log_dir: "logs"
  data_dir: "assets"
  output_dir: "assets"

processor:
  input_texts_file: "texts.csv"  # файл с токенизированными текстами
  input_anglicisms_file: "clean_anglicism.txt"  # файл со списком англицизмов
  text_column: "tokenized_text"  # колонка с текстами для анализа
  case_sensitive: false  # учитывать ли регистр при сравнении

logging:
  log_level: INFO
  format: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

output:
  file_name: "labeled_vocabulary.csv"  # имя выходного файла со словарем
  encoding: "utf-8"