# Файл: configs/parse_anglicism/analysis/main.yaml
# Конфигурация для анализатора англицизмов

# Настройки анализа
perform_advanced: true
analyze_patterns: true
compare_languages: true
top_n_languages: 5

# Настройки для парсера
patterns:
  language_section: "== Из (.*?) =="
  anglicism: "\\[\\[(.*?)\\]\\](.*?(?=\\[\\[|$))"
  through_english: "через англ"

# Настройки очистки
cleaning:
  lowercase: true
  remove_special_chars: true
  remove_duplicates: true

# Настройки категорий длины слов
length_categories:
  bins: [0, 4, 8, 12, 100]
  labels: ['Короткие (1-4)', 'Средние (5-8)', 'Длинные (9-12)', 'Очень длинные (>12)']

# Настройки буквенных паттернов
letter_patterns:
  analyze_suffixes: true
  analyze_prefixes: true
  analyze_bigrams: true
  prefix_length: 2
  suffix_length: 2
  top_n: 10

# Настройки путей
paths:
  data_dir: "data"
  output_dir: "outputs"
  logs_dir: "logs"
  visualization_dir: "outputs/visualization"