defaults:
  - _self_

paths:
  log_dir: "logs"
  data_dir: "data"

parser:
  query: "РБК"
  project: "rbcnews"
  category: "TopRbcRu_economics"
  material: ""
  dateFrom: "2025-02-02"
  dateTo: "2025-02-03"
  initial_page: 0
  max_pages: 2
  include_text: true

logging:
  log_level: INFO
  format: "[%(asctime)s][%(name)s][%(levelname)s] - %(message)s"
  date_format: "%Y-%m-%d %H:%M:%S"

output:
  file_prefix: "rbc_articles"
  encoding: "utf-8"